# Generated by Django 3.1.4 on 2021-02-03 18:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('triangle', '0002_auther_quote'),
    ]

    operations = [
        migrations.AlterField(
            model_name='quote',
            name='quote',
            field=models.TextField(verbose_name='quote'),
        ),
    ]
