# Generated by Django 3.1.4 on 2021-02-22 11:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('triangle', '0003_auto_20210203_2039'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('from_email', models.EmailField(blank=True, default='test@test.com', max_length=254, null=True, verbose_name='mail')),
                ('subject', models.CharField(max_length=200, verbose_name='subject')),
                ('message', models.TextField(help_text='message', max_length=1000, verbose_name='message')),
                ('result', models.CharField(blank=True, max_length=100, null=True, verbose_name='subject')),
            ],
        ),
    ]
