# Generated by Django 3.1.4 on 2021-02-22 12:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('triangle', '0004_contact'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contact',
            name='result',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='result'),
        ),
    ]
