# Generated by Django 3.1.4 on 2020-12-27 09:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Peson',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=200, verbose_name='username')),
                ('email', models.CharField(max_length=100, verbose_name='email')),
                ('password', models.CharField(max_length=100, verbose_name='password')),
            ],
            options={
                'ordering': ['username', 'email'],
            },
        ),
    ]
