# Generated by Django 3.1.4 on 2020-12-27 09:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0002_peson'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Peson',
            new_name='Person',
        ),
    ]
