# Generated by Django 3.1.4 on 2021-01-10 13:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('person', '0002_auto_20210104_1043'),
    ]

    operations = [
        migrations.CreateModel(
            name='Log_midlware',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('path', models.CharField(max_length=200, verbose_name='path')),
                ('method', models.CharField(max_length=100, verbose_name='method')),
                ('timestamp', models.FloatField(verbose_name='timestamp')),
            ],
            options={
                'ordering': ['path', 'method', 'timestamp'],
            },
        ),
    ]
