# Generated by Django 3.1.5 on 2021-01-14 15:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('person', '0003_log_midlware'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='log_midlware',
            options={'ordering': ['-timestamp', 'method', 'path']},
        ),
        migrations.AlterField(
            model_name='log_midlware',
            name='timestamp',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
